"""Contains all the data models used in inputs/outputs"""

from .delete_by_org_api_keys_by_id_response_200 import DeleteByOrgApiKeysByIdResponse200
from .delete_by_org_api_keys_by_id_response_400 import DeleteByOrgApiKeysByIdResponse400
from .delete_by_org_api_keys_by_id_response_400_error import DeleteByOrgApiKeysByIdResponse400Error
from .delete_by_org_api_keys_by_id_response_400_error_details import DeleteByOrgApiKeysByIdResponse400ErrorDetails
from .delete_by_org_api_keys_by_id_response_401 import DeleteByOrgApiKeysByIdResponse401
from .delete_by_org_api_keys_by_id_response_401_error import DeleteByOrgApiKeysByIdResponse401Error
from .delete_by_org_api_keys_by_id_response_401_error_details import DeleteByOrgApiKeysByIdResponse401ErrorDetails
from .delete_by_org_api_keys_by_id_response_403 import DeleteByOrgApiKeysByIdResponse403
from .delete_by_org_api_keys_by_id_response_403_error import DeleteByOrgApiKeysByIdResponse403Error
from .delete_by_org_api_keys_by_id_response_403_error_details import DeleteByOrgApiKeysByIdResponse403ErrorDetails
from .delete_by_org_api_keys_by_id_response_404 import DeleteByOrgApiKeysByIdResponse404
from .delete_by_org_api_keys_by_id_response_404_error import DeleteByOrgApiKeysByIdResponse404Error
from .delete_by_org_api_keys_by_id_response_404_error_details import DeleteByOrgApiKeysByIdResponse404ErrorDetails
from .delete_by_org_api_keys_by_id_response_406 import DeleteByOrgApiKeysByIdResponse406
from .delete_by_org_api_keys_by_id_response_406_error import DeleteByOrgApiKeysByIdResponse406Error
from .delete_by_org_api_keys_by_id_response_406_error_details import DeleteByOrgApiKeysByIdResponse406ErrorDetails
from .delete_by_org_api_keys_by_id_response_409 import DeleteByOrgApiKeysByIdResponse409
from .delete_by_org_api_keys_by_id_response_409_error import DeleteByOrgApiKeysByIdResponse409Error
from .delete_by_org_api_keys_by_id_response_409_error_details import DeleteByOrgApiKeysByIdResponse409ErrorDetails
from .delete_by_org_api_keys_by_id_response_500 import DeleteByOrgApiKeysByIdResponse500
from .delete_by_org_api_keys_by_id_response_500_error import DeleteByOrgApiKeysByIdResponse500Error
from .delete_by_org_api_keys_by_id_response_500_error_details import DeleteByOrgApiKeysByIdResponse500ErrorDetails
from .delete_by_org_by_repo_branches_by_branch_response_200 import DeleteByOrgByRepoBranchesByBranchResponse200
from .delete_by_org_by_repo_branches_by_branch_response_400 import DeleteByOrgByRepoBranchesByBranchResponse400
from .delete_by_org_by_repo_branches_by_branch_response_400_error import (
    DeleteByOrgByRepoBranchesByBranchResponse400Error,
)
from .delete_by_org_by_repo_branches_by_branch_response_400_error_details import (
    DeleteByOrgByRepoBranchesByBranchResponse400ErrorDetails,
)
from .delete_by_org_by_repo_branches_by_branch_response_401 import DeleteByOrgByRepoBranchesByBranchResponse401
from .delete_by_org_by_repo_branches_by_branch_response_401_error import (
    DeleteByOrgByRepoBranchesByBranchResponse401Error,
)
from .delete_by_org_by_repo_branches_by_branch_response_401_error_details import (
    DeleteByOrgByRepoBranchesByBranchResponse401ErrorDetails,
)
from .delete_by_org_by_repo_branches_by_branch_response_403 import DeleteByOrgByRepoBranchesByBranchResponse403
from .delete_by_org_by_repo_branches_by_branch_response_403_error import (
    DeleteByOrgByRepoBranchesByBranchResponse403Error,
)
from .delete_by_org_by_repo_branches_by_branch_response_403_error_details import (
    DeleteByOrgByRepoBranchesByBranchResponse403ErrorDetails,
)
from .delete_by_org_by_repo_branches_by_branch_response_404 import DeleteByOrgByRepoBranchesByBranchResponse404
from .delete_by_org_by_repo_branches_by_branch_response_404_error import (
    DeleteByOrgByRepoBranchesByBranchResponse404Error,
)
from .delete_by_org_by_repo_branches_by_branch_response_404_error_details import (
    DeleteByOrgByRepoBranchesByBranchResponse404ErrorDetails,
)
from .delete_by_org_by_repo_branches_by_branch_response_406 import DeleteByOrgByRepoBranchesByBranchResponse406
from .delete_by_org_by_repo_branches_by_branch_response_406_error import (
    DeleteByOrgByRepoBranchesByBranchResponse406Error,
)
from .delete_by_org_by_repo_branches_by_branch_response_406_error_details import (
    DeleteByOrgByRepoBranchesByBranchResponse406ErrorDetails,
)
from .delete_by_org_by_repo_branches_by_branch_response_409 import DeleteByOrgByRepoBranchesByBranchResponse409
from .delete_by_org_by_repo_branches_by_branch_response_409_error import (
    DeleteByOrgByRepoBranchesByBranchResponse409Error,
)
from .delete_by_org_by_repo_branches_by_branch_response_409_error_details import (
    DeleteByOrgByRepoBranchesByBranchResponse409ErrorDetails,
)
from .delete_by_org_by_repo_branches_by_branch_response_500 import DeleteByOrgByRepoBranchesByBranchResponse500
from .delete_by_org_by_repo_branches_by_branch_response_500_error import (
    DeleteByOrgByRepoBranchesByBranchResponse500Error,
)
from .delete_by_org_by_repo_branches_by_branch_response_500_error_details import (
    DeleteByOrgByRepoBranchesByBranchResponse500ErrorDetails,
)
from .delete_by_org_by_repo_response_200 import DeleteByOrgByRepoResponse200
from .delete_by_org_by_repo_response_400 import DeleteByOrgByRepoResponse400
from .delete_by_org_by_repo_response_400_error import DeleteByOrgByRepoResponse400Error
from .delete_by_org_by_repo_response_400_error_details import DeleteByOrgByRepoResponse400ErrorDetails
from .delete_by_org_by_repo_response_401 import DeleteByOrgByRepoResponse401
from .delete_by_org_by_repo_response_401_error import DeleteByOrgByRepoResponse401Error
from .delete_by_org_by_repo_response_401_error_details import DeleteByOrgByRepoResponse401ErrorDetails
from .delete_by_org_by_repo_response_403 import DeleteByOrgByRepoResponse403
from .delete_by_org_by_repo_response_403_error import DeleteByOrgByRepoResponse403Error
from .delete_by_org_by_repo_response_403_error_details import DeleteByOrgByRepoResponse403ErrorDetails
from .delete_by_org_by_repo_response_404 import DeleteByOrgByRepoResponse404
from .delete_by_org_by_repo_response_404_error import DeleteByOrgByRepoResponse404Error
from .delete_by_org_by_repo_response_404_error_details import DeleteByOrgByRepoResponse404ErrorDetails
from .delete_by_org_by_repo_response_406 import DeleteByOrgByRepoResponse406
from .delete_by_org_by_repo_response_406_error import DeleteByOrgByRepoResponse406Error
from .delete_by_org_by_repo_response_406_error_details import DeleteByOrgByRepoResponse406ErrorDetails
from .delete_by_org_by_repo_response_409 import DeleteByOrgByRepoResponse409
from .delete_by_org_by_repo_response_409_error import DeleteByOrgByRepoResponse409Error
from .delete_by_org_by_repo_response_409_error_details import DeleteByOrgByRepoResponse409ErrorDetails
from .delete_by_org_by_repo_response_500 import DeleteByOrgByRepoResponse500
from .delete_by_org_by_repo_response_500_error import DeleteByOrgByRepoResponse500Error
from .delete_by_org_by_repo_response_500_error_details import DeleteByOrgByRepoResponse500ErrorDetails
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_200 import DeleteByOrgByRepoWebhooksByWebhookIdResponse200
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_400 import DeleteByOrgByRepoWebhooksByWebhookIdResponse400
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_400_error import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse400Error,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_400_error_details import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse400ErrorDetails,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_401 import DeleteByOrgByRepoWebhooksByWebhookIdResponse401
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_401_error import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse401Error,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_401_error_details import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse401ErrorDetails,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_403 import DeleteByOrgByRepoWebhooksByWebhookIdResponse403
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_403_error import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse403Error,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_403_error_details import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse403ErrorDetails,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_404 import DeleteByOrgByRepoWebhooksByWebhookIdResponse404
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_404_error import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse404Error,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_404_error_details import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse404ErrorDetails,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_406 import DeleteByOrgByRepoWebhooksByWebhookIdResponse406
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_406_error import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse406Error,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_406_error_details import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse406ErrorDetails,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_409 import DeleteByOrgByRepoWebhooksByWebhookIdResponse409
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_409_error import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse409Error,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_409_error_details import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse409ErrorDetails,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_500 import DeleteByOrgByRepoWebhooksByWebhookIdResponse500
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_500_error import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse500Error,
)
from .delete_by_org_by_repo_webhooks_by_webhook_id_response_500_error_details import (
    DeleteByOrgByRepoWebhooksByWebhookIdResponse500ErrorDetails,
)
from .get_by_org_api_keys_response_200 import GetByOrgApiKeysResponse200
from .get_by_org_api_keys_response_200_api_keys_item import GetByOrgApiKeysResponse200ApiKeysItem
from .get_by_org_api_keys_response_400 import GetByOrgApiKeysResponse400
from .get_by_org_api_keys_response_400_error import GetByOrgApiKeysResponse400Error
from .get_by_org_api_keys_response_400_error_details import GetByOrgApiKeysResponse400ErrorDetails
from .get_by_org_api_keys_response_401 import GetByOrgApiKeysResponse401
from .get_by_org_api_keys_response_401_error import GetByOrgApiKeysResponse401Error
from .get_by_org_api_keys_response_401_error_details import GetByOrgApiKeysResponse401ErrorDetails
from .get_by_org_api_keys_response_403 import GetByOrgApiKeysResponse403
from .get_by_org_api_keys_response_403_error import GetByOrgApiKeysResponse403Error
from .get_by_org_api_keys_response_403_error_details import GetByOrgApiKeysResponse403ErrorDetails
from .get_by_org_api_keys_response_404 import GetByOrgApiKeysResponse404
from .get_by_org_api_keys_response_404_error import GetByOrgApiKeysResponse404Error
from .get_by_org_api_keys_response_404_error_details import GetByOrgApiKeysResponse404ErrorDetails
from .get_by_org_api_keys_response_406 import GetByOrgApiKeysResponse406
from .get_by_org_api_keys_response_406_error import GetByOrgApiKeysResponse406Error
from .get_by_org_api_keys_response_406_error_details import GetByOrgApiKeysResponse406ErrorDetails
from .get_by_org_api_keys_response_409 import GetByOrgApiKeysResponse409
from .get_by_org_api_keys_response_409_error import GetByOrgApiKeysResponse409Error
from .get_by_org_api_keys_response_409_error_details import GetByOrgApiKeysResponse409ErrorDetails
from .get_by_org_api_keys_response_500 import GetByOrgApiKeysResponse500
from .get_by_org_api_keys_response_500_error import GetByOrgApiKeysResponse500Error
from .get_by_org_api_keys_response_500_error_details import GetByOrgApiKeysResponse500ErrorDetails
from .get_by_org_by_repo_branches_response_200 import GetByOrgByRepoBranchesResponse200
from .get_by_org_by_repo_branches_response_200_branches_item import GetByOrgByRepoBranchesResponse200BranchesItem
from .get_by_org_by_repo_branches_response_400 import GetByOrgByRepoBranchesResponse400
from .get_by_org_by_repo_branches_response_400_error import GetByOrgByRepoBranchesResponse400Error
from .get_by_org_by_repo_branches_response_400_error_details import GetByOrgByRepoBranchesResponse400ErrorDetails
from .get_by_org_by_repo_branches_response_401 import GetByOrgByRepoBranchesResponse401
from .get_by_org_by_repo_branches_response_401_error import GetByOrgByRepoBranchesResponse401Error
from .get_by_org_by_repo_branches_response_401_error_details import GetByOrgByRepoBranchesResponse401ErrorDetails
from .get_by_org_by_repo_branches_response_403 import GetByOrgByRepoBranchesResponse403
from .get_by_org_by_repo_branches_response_403_error import GetByOrgByRepoBranchesResponse403Error
from .get_by_org_by_repo_branches_response_403_error_details import GetByOrgByRepoBranchesResponse403ErrorDetails
from .get_by_org_by_repo_branches_response_404 import GetByOrgByRepoBranchesResponse404
from .get_by_org_by_repo_branches_response_404_error import GetByOrgByRepoBranchesResponse404Error
from .get_by_org_by_repo_branches_response_404_error_details import GetByOrgByRepoBranchesResponse404ErrorDetails
from .get_by_org_by_repo_branches_response_406 import GetByOrgByRepoBranchesResponse406
from .get_by_org_by_repo_branches_response_406_error import GetByOrgByRepoBranchesResponse406Error
from .get_by_org_by_repo_branches_response_406_error_details import GetByOrgByRepoBranchesResponse406ErrorDetails
from .get_by_org_by_repo_branches_response_409 import GetByOrgByRepoBranchesResponse409
from .get_by_org_by_repo_branches_response_409_error import GetByOrgByRepoBranchesResponse409Error
from .get_by_org_by_repo_branches_response_409_error_details import GetByOrgByRepoBranchesResponse409ErrorDetails
from .get_by_org_by_repo_branches_response_500 import GetByOrgByRepoBranchesResponse500
from .get_by_org_by_repo_branches_response_500_error import GetByOrgByRepoBranchesResponse500Error
from .get_by_org_by_repo_branches_response_500_error_details import GetByOrgByRepoBranchesResponse500ErrorDetails
from .get_by_org_by_repo_commits_by_sha_response_200 import GetByOrgByRepoCommitsByShaResponse200
from .get_by_org_by_repo_commits_by_sha_response_200_author import GetByOrgByRepoCommitsByShaResponse200Author
from .get_by_org_by_repo_commits_by_sha_response_200_committer import GetByOrgByRepoCommitsByShaResponse200Committer
from .get_by_org_by_repo_commits_by_sha_response_400 import GetByOrgByRepoCommitsByShaResponse400
from .get_by_org_by_repo_commits_by_sha_response_400_error import GetByOrgByRepoCommitsByShaResponse400Error
from .get_by_org_by_repo_commits_by_sha_response_400_error_details import (
    GetByOrgByRepoCommitsByShaResponse400ErrorDetails,
)
from .get_by_org_by_repo_commits_by_sha_response_401 import GetByOrgByRepoCommitsByShaResponse401
from .get_by_org_by_repo_commits_by_sha_response_401_error import GetByOrgByRepoCommitsByShaResponse401Error
from .get_by_org_by_repo_commits_by_sha_response_401_error_details import (
    GetByOrgByRepoCommitsByShaResponse401ErrorDetails,
)
from .get_by_org_by_repo_commits_by_sha_response_403 import GetByOrgByRepoCommitsByShaResponse403
from .get_by_org_by_repo_commits_by_sha_response_403_error import GetByOrgByRepoCommitsByShaResponse403Error
from .get_by_org_by_repo_commits_by_sha_response_403_error_details import (
    GetByOrgByRepoCommitsByShaResponse403ErrorDetails,
)
from .get_by_org_by_repo_commits_by_sha_response_404 import GetByOrgByRepoCommitsByShaResponse404
from .get_by_org_by_repo_commits_by_sha_response_404_error import GetByOrgByRepoCommitsByShaResponse404Error
from .get_by_org_by_repo_commits_by_sha_response_404_error_details import (
    GetByOrgByRepoCommitsByShaResponse404ErrorDetails,
)
from .get_by_org_by_repo_commits_by_sha_response_406 import GetByOrgByRepoCommitsByShaResponse406
from .get_by_org_by_repo_commits_by_sha_response_406_error import GetByOrgByRepoCommitsByShaResponse406Error
from .get_by_org_by_repo_commits_by_sha_response_406_error_details import (
    GetByOrgByRepoCommitsByShaResponse406ErrorDetails,
)
from .get_by_org_by_repo_commits_by_sha_response_409 import GetByOrgByRepoCommitsByShaResponse409
from .get_by_org_by_repo_commits_by_sha_response_409_error import GetByOrgByRepoCommitsByShaResponse409Error
from .get_by_org_by_repo_commits_by_sha_response_409_error_details import (
    GetByOrgByRepoCommitsByShaResponse409ErrorDetails,
)
from .get_by_org_by_repo_commits_by_sha_response_500 import GetByOrgByRepoCommitsByShaResponse500
from .get_by_org_by_repo_commits_by_sha_response_500_error import GetByOrgByRepoCommitsByShaResponse500Error
from .get_by_org_by_repo_commits_by_sha_response_500_error_details import (
    GetByOrgByRepoCommitsByShaResponse500ErrorDetails,
)
from .get_by_org_by_repo_commits_response_200 import GetByOrgByRepoCommitsResponse200
from .get_by_org_by_repo_commits_response_200_commits_item import GetByOrgByRepoCommitsResponse200CommitsItem
from .get_by_org_by_repo_commits_response_200_commits_item_author import (
    GetByOrgByRepoCommitsResponse200CommitsItemAuthor,
)
from .get_by_org_by_repo_commits_response_200_commits_item_committer import (
    GetByOrgByRepoCommitsResponse200CommitsItemCommitter,
)
from .get_by_org_by_repo_commits_response_400 import GetByOrgByRepoCommitsResponse400
from .get_by_org_by_repo_commits_response_400_error import GetByOrgByRepoCommitsResponse400Error
from .get_by_org_by_repo_commits_response_400_error_details import GetByOrgByRepoCommitsResponse400ErrorDetails
from .get_by_org_by_repo_commits_response_401 import GetByOrgByRepoCommitsResponse401
from .get_by_org_by_repo_commits_response_401_error import GetByOrgByRepoCommitsResponse401Error
from .get_by_org_by_repo_commits_response_401_error_details import GetByOrgByRepoCommitsResponse401ErrorDetails
from .get_by_org_by_repo_commits_response_403 import GetByOrgByRepoCommitsResponse403
from .get_by_org_by_repo_commits_response_403_error import GetByOrgByRepoCommitsResponse403Error
from .get_by_org_by_repo_commits_response_403_error_details import GetByOrgByRepoCommitsResponse403ErrorDetails
from .get_by_org_by_repo_commits_response_404 import GetByOrgByRepoCommitsResponse404
from .get_by_org_by_repo_commits_response_404_error import GetByOrgByRepoCommitsResponse404Error
from .get_by_org_by_repo_commits_response_404_error_details import GetByOrgByRepoCommitsResponse404ErrorDetails
from .get_by_org_by_repo_commits_response_406 import GetByOrgByRepoCommitsResponse406
from .get_by_org_by_repo_commits_response_406_error import GetByOrgByRepoCommitsResponse406Error
from .get_by_org_by_repo_commits_response_406_error_details import GetByOrgByRepoCommitsResponse406ErrorDetails
from .get_by_org_by_repo_commits_response_409 import GetByOrgByRepoCommitsResponse409
from .get_by_org_by_repo_commits_response_409_error import GetByOrgByRepoCommitsResponse409Error
from .get_by_org_by_repo_commits_response_409_error_details import GetByOrgByRepoCommitsResponse409ErrorDetails
from .get_by_org_by_repo_commits_response_500 import GetByOrgByRepoCommitsResponse500
from .get_by_org_by_repo_commits_response_500_error import GetByOrgByRepoCommitsResponse500Error
from .get_by_org_by_repo_commits_response_500_error_details import GetByOrgByRepoCommitsResponse500ErrorDetails
from .get_by_org_by_repo_content_response_200_type_0 import GetByOrgByRepoContentResponse200Type0
from .get_by_org_by_repo_content_response_200_type_1 import GetByOrgByRepoContentResponse200Type1
from .get_by_org_by_repo_content_response_200_type_2 import GetByOrgByRepoContentResponse200Type2
from .get_by_org_by_repo_content_response_200_type_2_entries_item_type_0 import (
    GetByOrgByRepoContentResponse200Type2EntriesItemType0,
)
from .get_by_org_by_repo_content_response_200_type_2_entries_item_type_1 import (
    GetByOrgByRepoContentResponse200Type2EntriesItemType1,
)
from .get_by_org_by_repo_content_response_200_type_2_entries_item_type_2 import (
    GetByOrgByRepoContentResponse200Type2EntriesItemType2,
)
from .get_by_org_by_repo_content_response_400 import GetByOrgByRepoContentResponse400
from .get_by_org_by_repo_content_response_400_error import GetByOrgByRepoContentResponse400Error
from .get_by_org_by_repo_content_response_400_error_details import GetByOrgByRepoContentResponse400ErrorDetails
from .get_by_org_by_repo_content_response_401 import GetByOrgByRepoContentResponse401
from .get_by_org_by_repo_content_response_401_error import GetByOrgByRepoContentResponse401Error
from .get_by_org_by_repo_content_response_401_error_details import GetByOrgByRepoContentResponse401ErrorDetails
from .get_by_org_by_repo_content_response_403 import GetByOrgByRepoContentResponse403
from .get_by_org_by_repo_content_response_403_error import GetByOrgByRepoContentResponse403Error
from .get_by_org_by_repo_content_response_403_error_details import GetByOrgByRepoContentResponse403ErrorDetails
from .get_by_org_by_repo_content_response_404 import GetByOrgByRepoContentResponse404
from .get_by_org_by_repo_content_response_404_error import GetByOrgByRepoContentResponse404Error
from .get_by_org_by_repo_content_response_404_error_details import GetByOrgByRepoContentResponse404ErrorDetails
from .get_by_org_by_repo_content_response_406 import GetByOrgByRepoContentResponse406
from .get_by_org_by_repo_content_response_406_error import GetByOrgByRepoContentResponse406Error
from .get_by_org_by_repo_content_response_406_error_details import GetByOrgByRepoContentResponse406ErrorDetails
from .get_by_org_by_repo_content_response_409 import GetByOrgByRepoContentResponse409
from .get_by_org_by_repo_content_response_409_error import GetByOrgByRepoContentResponse409Error
from .get_by_org_by_repo_content_response_409_error_details import GetByOrgByRepoContentResponse409ErrorDetails
from .get_by_org_by_repo_content_response_500 import GetByOrgByRepoContentResponse500
from .get_by_org_by_repo_content_response_500_error import GetByOrgByRepoContentResponse500Error
from .get_by_org_by_repo_content_response_500_error_details import GetByOrgByRepoContentResponse500ErrorDetails
from .get_by_org_by_repo_response_200 import GetByOrgByRepoResponse200
from .get_by_org_by_repo_response_200_upstream_type_0 import GetByOrgByRepoResponse200UpstreamType0
from .get_by_org_by_repo_response_200_upstream_type_0_autosync_type_0 import (
    GetByOrgByRepoResponse200UpstreamType0AutosyncType0,
)
from .get_by_org_by_repo_response_200_upstream_type_0_autosync_type_0_resolution_strategy import (
    GetByOrgByRepoResponse200UpstreamType0AutosyncType0ResolutionStrategy,
)
from .get_by_org_by_repo_response_400 import GetByOrgByRepoResponse400
from .get_by_org_by_repo_response_400_error import GetByOrgByRepoResponse400Error
from .get_by_org_by_repo_response_400_error_details import GetByOrgByRepoResponse400ErrorDetails
from .get_by_org_by_repo_response_401 import GetByOrgByRepoResponse401
from .get_by_org_by_repo_response_401_error import GetByOrgByRepoResponse401Error
from .get_by_org_by_repo_response_401_error_details import GetByOrgByRepoResponse401ErrorDetails
from .get_by_org_by_repo_response_403 import GetByOrgByRepoResponse403
from .get_by_org_by_repo_response_403_error import GetByOrgByRepoResponse403Error
from .get_by_org_by_repo_response_403_error_details import GetByOrgByRepoResponse403ErrorDetails
from .get_by_org_by_repo_response_404 import GetByOrgByRepoResponse404
from .get_by_org_by_repo_response_404_error import GetByOrgByRepoResponse404Error
from .get_by_org_by_repo_response_404_error_details import GetByOrgByRepoResponse404ErrorDetails
from .get_by_org_by_repo_response_406 import GetByOrgByRepoResponse406
from .get_by_org_by_repo_response_406_error import GetByOrgByRepoResponse406Error
from .get_by_org_by_repo_response_406_error_details import GetByOrgByRepoResponse406ErrorDetails
from .get_by_org_by_repo_response_409 import GetByOrgByRepoResponse409
from .get_by_org_by_repo_response_409_error import GetByOrgByRepoResponse409Error
from .get_by_org_by_repo_response_409_error_details import GetByOrgByRepoResponse409ErrorDetails
from .get_by_org_by_repo_response_500 import GetByOrgByRepoResponse500
from .get_by_org_by_repo_response_500_error import GetByOrgByRepoResponse500Error
from .get_by_org_by_repo_response_500_error_details import GetByOrgByRepoResponse500ErrorDetails
from .get_by_org_by_repo_webhooks_response_200 import GetByOrgByRepoWebhooksResponse200
from .get_by_org_by_repo_webhooks_response_200_webhooks_item import GetByOrgByRepoWebhooksResponse200WebhooksItem
from .get_by_org_by_repo_webhooks_response_200_webhooks_item_events_item import (
    GetByOrgByRepoWebhooksResponse200WebhooksItemEventsItem,
)
from .get_by_org_by_repo_webhooks_response_400 import GetByOrgByRepoWebhooksResponse400
from .get_by_org_by_repo_webhooks_response_400_error import GetByOrgByRepoWebhooksResponse400Error
from .get_by_org_by_repo_webhooks_response_400_error_details import GetByOrgByRepoWebhooksResponse400ErrorDetails
from .get_by_org_by_repo_webhooks_response_401 import GetByOrgByRepoWebhooksResponse401
from .get_by_org_by_repo_webhooks_response_401_error import GetByOrgByRepoWebhooksResponse401Error
from .get_by_org_by_repo_webhooks_response_401_error_details import GetByOrgByRepoWebhooksResponse401ErrorDetails
from .get_by_org_by_repo_webhooks_response_403 import GetByOrgByRepoWebhooksResponse403
from .get_by_org_by_repo_webhooks_response_403_error import GetByOrgByRepoWebhooksResponse403Error
from .get_by_org_by_repo_webhooks_response_403_error_details import GetByOrgByRepoWebhooksResponse403ErrorDetails
from .get_by_org_by_repo_webhooks_response_404 import GetByOrgByRepoWebhooksResponse404
from .get_by_org_by_repo_webhooks_response_404_error import GetByOrgByRepoWebhooksResponse404Error
from .get_by_org_by_repo_webhooks_response_404_error_details import GetByOrgByRepoWebhooksResponse404ErrorDetails
from .get_by_org_by_repo_webhooks_response_406 import GetByOrgByRepoWebhooksResponse406
from .get_by_org_by_repo_webhooks_response_406_error import GetByOrgByRepoWebhooksResponse406Error
from .get_by_org_by_repo_webhooks_response_406_error_details import GetByOrgByRepoWebhooksResponse406ErrorDetails
from .get_by_org_by_repo_webhooks_response_409 import GetByOrgByRepoWebhooksResponse409
from .get_by_org_by_repo_webhooks_response_409_error import GetByOrgByRepoWebhooksResponse409Error
from .get_by_org_by_repo_webhooks_response_409_error_details import GetByOrgByRepoWebhooksResponse409ErrorDetails
from .get_by_org_by_repo_webhooks_response_500 import GetByOrgByRepoWebhooksResponse500
from .get_by_org_by_repo_webhooks_response_500_error import GetByOrgByRepoWebhooksResponse500Error
from .get_by_org_by_repo_webhooks_response_500_error_details import GetByOrgByRepoWebhooksResponse500ErrorDetails
from .get_by_org_repos_response_200 import GetByOrgReposResponse200
from .get_by_org_repos_response_200_repos_item import GetByOrgReposResponse200ReposItem
from .get_by_org_repos_response_200_repos_item_upstream_type_0 import GetByOrgReposResponse200ReposItemUpstreamType0
from .get_by_org_repos_response_200_repos_item_upstream_type_0_autosync_type_0 import (
    GetByOrgReposResponse200ReposItemUpstreamType0AutosyncType0,
)
from .get_by_org_repos_response_200_repos_item_upstream_type_0_autosync_type_0_resolution_strategy import (
    GetByOrgReposResponse200ReposItemUpstreamType0AutosyncType0ResolutionStrategy,
)
from .get_by_org_repos_response_400 import GetByOrgReposResponse400
from .get_by_org_repos_response_400_error import GetByOrgReposResponse400Error
from .get_by_org_repos_response_400_error_details import GetByOrgReposResponse400ErrorDetails
from .get_by_org_repos_response_401 import GetByOrgReposResponse401
from .get_by_org_repos_response_401_error import GetByOrgReposResponse401Error
from .get_by_org_repos_response_401_error_details import GetByOrgReposResponse401ErrorDetails
from .get_by_org_repos_response_403 import GetByOrgReposResponse403
from .get_by_org_repos_response_403_error import GetByOrgReposResponse403Error
from .get_by_org_repos_response_403_error_details import GetByOrgReposResponse403ErrorDetails
from .get_by_org_repos_response_404 import GetByOrgReposResponse404
from .get_by_org_repos_response_404_error import GetByOrgReposResponse404Error
from .get_by_org_repos_response_404_error_details import GetByOrgReposResponse404ErrorDetails
from .get_by_org_repos_response_406 import GetByOrgReposResponse406
from .get_by_org_repos_response_406_error import GetByOrgReposResponse406Error
from .get_by_org_repos_response_406_error_details import GetByOrgReposResponse406ErrorDetails
from .get_by_org_repos_response_409 import GetByOrgReposResponse409
from .get_by_org_repos_response_409_error import GetByOrgReposResponse409Error
from .get_by_org_repos_response_409_error_details import GetByOrgReposResponse409ErrorDetails
from .get_by_org_repos_response_500 import GetByOrgReposResponse500
from .get_by_org_repos_response_500_error import GetByOrgReposResponse500Error
from .get_by_org_repos_response_500_error_details import GetByOrgReposResponse500ErrorDetails
from .get_by_org_response_200 import GetByOrgResponse200
from .get_by_org_response_400 import GetByOrgResponse400
from .get_by_org_response_400_error import GetByOrgResponse400Error
from .get_by_org_response_400_error_details import GetByOrgResponse400ErrorDetails
from .get_by_org_response_401 import GetByOrgResponse401
from .get_by_org_response_401_error import GetByOrgResponse401Error
from .get_by_org_response_401_error_details import GetByOrgResponse401ErrorDetails
from .get_by_org_response_403 import GetByOrgResponse403
from .get_by_org_response_403_error import GetByOrgResponse403Error
from .get_by_org_response_403_error_details import GetByOrgResponse403ErrorDetails
from .get_by_org_response_404 import GetByOrgResponse404
from .get_by_org_response_404_error import GetByOrgResponse404Error
from .get_by_org_response_404_error_details import GetByOrgResponse404ErrorDetails
from .get_by_org_response_406 import GetByOrgResponse406
from .get_by_org_response_406_error import GetByOrgResponse406Error
from .get_by_org_response_406_error_details import GetByOrgResponse406ErrorDetails
from .get_by_org_response_409 import GetByOrgResponse409
from .get_by_org_response_409_error import GetByOrgResponse409Error
from .get_by_org_response_409_error_details import GetByOrgResponse409ErrorDetails
from .get_by_org_response_500 import GetByOrgResponse500
from .get_by_org_response_500_error import GetByOrgResponse500Error
from .get_by_org_response_500_error_details import GetByOrgResponse500ErrorDetails
from .patch_by_org_by_repo_body import PatchByOrgByRepoBody
from .patch_by_org_by_repo_body_upstream_type_0 import PatchByOrgByRepoBodyUpstreamType0
from .patch_by_org_by_repo_body_upstream_type_0_autosync_type_0 import PatchByOrgByRepoBodyUpstreamType0AutosyncType0
from .patch_by_org_by_repo_body_upstream_type_0_autosync_type_0_resolution_strategy import (
    PatchByOrgByRepoBodyUpstreamType0AutosyncType0ResolutionStrategy,
)
from .patch_by_org_by_repo_response_200 import PatchByOrgByRepoResponse200
from .patch_by_org_by_repo_response_200_upstream_type_0 import PatchByOrgByRepoResponse200UpstreamType0
from .patch_by_org_by_repo_response_200_upstream_type_0_autosync_type_0 import (
    PatchByOrgByRepoResponse200UpstreamType0AutosyncType0,
)
from .patch_by_org_by_repo_response_200_upstream_type_0_autosync_type_0_resolution_strategy import (
    PatchByOrgByRepoResponse200UpstreamType0AutosyncType0ResolutionStrategy,
)
from .patch_by_org_by_repo_response_400 import PatchByOrgByRepoResponse400
from .patch_by_org_by_repo_response_400_error import PatchByOrgByRepoResponse400Error
from .patch_by_org_by_repo_response_400_error_details import PatchByOrgByRepoResponse400ErrorDetails
from .patch_by_org_by_repo_response_401 import PatchByOrgByRepoResponse401
from .patch_by_org_by_repo_response_401_error import PatchByOrgByRepoResponse401Error
from .patch_by_org_by_repo_response_401_error_details import PatchByOrgByRepoResponse401ErrorDetails
from .patch_by_org_by_repo_response_403 import PatchByOrgByRepoResponse403
from .patch_by_org_by_repo_response_403_error import PatchByOrgByRepoResponse403Error
from .patch_by_org_by_repo_response_403_error_details import PatchByOrgByRepoResponse403ErrorDetails
from .patch_by_org_by_repo_response_404 import PatchByOrgByRepoResponse404
from .patch_by_org_by_repo_response_404_error import PatchByOrgByRepoResponse404Error
from .patch_by_org_by_repo_response_404_error_details import PatchByOrgByRepoResponse404ErrorDetails
from .patch_by_org_by_repo_response_406 import PatchByOrgByRepoResponse406
from .patch_by_org_by_repo_response_406_error import PatchByOrgByRepoResponse406Error
from .patch_by_org_by_repo_response_406_error_details import PatchByOrgByRepoResponse406ErrorDetails
from .patch_by_org_by_repo_response_409 import PatchByOrgByRepoResponse409
from .patch_by_org_by_repo_response_409_error import PatchByOrgByRepoResponse409Error
from .patch_by_org_by_repo_response_409_error_details import PatchByOrgByRepoResponse409ErrorDetails
from .patch_by_org_by_repo_response_500 import PatchByOrgByRepoResponse500
from .patch_by_org_by_repo_response_500_error import PatchByOrgByRepoResponse500Error
from .patch_by_org_by_repo_response_500_error_details import PatchByOrgByRepoResponse500ErrorDetails
from .post_by_org_api_keys_body import PostByOrgApiKeysBody
from .post_by_org_api_keys_body_scopes_item import PostByOrgApiKeysBodyScopesItem
from .post_by_org_api_keys_response_201 import PostByOrgApiKeysResponse201
from .post_by_org_api_keys_response_400 import PostByOrgApiKeysResponse400
from .post_by_org_api_keys_response_400_error import PostByOrgApiKeysResponse400Error
from .post_by_org_api_keys_response_400_error_details import PostByOrgApiKeysResponse400ErrorDetails
from .post_by_org_api_keys_response_401 import PostByOrgApiKeysResponse401
from .post_by_org_api_keys_response_401_error import PostByOrgApiKeysResponse401Error
from .post_by_org_api_keys_response_401_error_details import PostByOrgApiKeysResponse401ErrorDetails
from .post_by_org_api_keys_response_403 import PostByOrgApiKeysResponse403
from .post_by_org_api_keys_response_403_error import PostByOrgApiKeysResponse403Error
from .post_by_org_api_keys_response_403_error_details import PostByOrgApiKeysResponse403ErrorDetails
from .post_by_org_api_keys_response_404 import PostByOrgApiKeysResponse404
from .post_by_org_api_keys_response_404_error import PostByOrgApiKeysResponse404Error
from .post_by_org_api_keys_response_404_error_details import PostByOrgApiKeysResponse404ErrorDetails
from .post_by_org_api_keys_response_406 import PostByOrgApiKeysResponse406
from .post_by_org_api_keys_response_406_error import PostByOrgApiKeysResponse406Error
from .post_by_org_api_keys_response_406_error_details import PostByOrgApiKeysResponse406ErrorDetails
from .post_by_org_api_keys_response_409 import PostByOrgApiKeysResponse409
from .post_by_org_api_keys_response_409_error import PostByOrgApiKeysResponse409Error
from .post_by_org_api_keys_response_409_error_details import PostByOrgApiKeysResponse409ErrorDetails
from .post_by_org_api_keys_response_500 import PostByOrgApiKeysResponse500
from .post_by_org_api_keys_response_500_error import PostByOrgApiKeysResponse500Error
from .post_by_org_api_keys_response_500_error_details import PostByOrgApiKeysResponse500ErrorDetails
from .post_by_org_by_repo_branches_body import PostByOrgByRepoBranchesBody
from .post_by_org_by_repo_branches_response_201 import PostByOrgByRepoBranchesResponse201
from .post_by_org_by_repo_branches_response_400 import PostByOrgByRepoBranchesResponse400
from .post_by_org_by_repo_branches_response_400_error import PostByOrgByRepoBranchesResponse400Error
from .post_by_org_by_repo_branches_response_400_error_details import PostByOrgByRepoBranchesResponse400ErrorDetails
from .post_by_org_by_repo_branches_response_401 import PostByOrgByRepoBranchesResponse401
from .post_by_org_by_repo_branches_response_401_error import PostByOrgByRepoBranchesResponse401Error
from .post_by_org_by_repo_branches_response_401_error_details import PostByOrgByRepoBranchesResponse401ErrorDetails
from .post_by_org_by_repo_branches_response_403 import PostByOrgByRepoBranchesResponse403
from .post_by_org_by_repo_branches_response_403_error import PostByOrgByRepoBranchesResponse403Error
from .post_by_org_by_repo_branches_response_403_error_details import PostByOrgByRepoBranchesResponse403ErrorDetails
from .post_by_org_by_repo_branches_response_404 import PostByOrgByRepoBranchesResponse404
from .post_by_org_by_repo_branches_response_404_error import PostByOrgByRepoBranchesResponse404Error
from .post_by_org_by_repo_branches_response_404_error_details import PostByOrgByRepoBranchesResponse404ErrorDetails
from .post_by_org_by_repo_branches_response_406 import PostByOrgByRepoBranchesResponse406
from .post_by_org_by_repo_branches_response_406_error import PostByOrgByRepoBranchesResponse406Error
from .post_by_org_by_repo_branches_response_406_error_details import PostByOrgByRepoBranchesResponse406ErrorDetails
from .post_by_org_by_repo_branches_response_409 import PostByOrgByRepoBranchesResponse409
from .post_by_org_by_repo_branches_response_409_error import PostByOrgByRepoBranchesResponse409Error
from .post_by_org_by_repo_branches_response_409_error_details import PostByOrgByRepoBranchesResponse409ErrorDetails
from .post_by_org_by_repo_branches_response_500 import PostByOrgByRepoBranchesResponse500
from .post_by_org_by_repo_branches_response_500_error import PostByOrgByRepoBranchesResponse500Error
from .post_by_org_by_repo_branches_response_500_error_details import PostByOrgByRepoBranchesResponse500ErrorDetails
from .post_by_org_by_repo_webhooks_body import PostByOrgByRepoWebhooksBody
from .post_by_org_by_repo_webhooks_body_events_item import PostByOrgByRepoWebhooksBodyEventsItem
from .post_by_org_by_repo_webhooks_response_201 import PostByOrgByRepoWebhooksResponse201
from .post_by_org_by_repo_webhooks_response_201_events_item import PostByOrgByRepoWebhooksResponse201EventsItem
from .post_by_org_by_repo_webhooks_response_400 import PostByOrgByRepoWebhooksResponse400
from .post_by_org_by_repo_webhooks_response_400_error import PostByOrgByRepoWebhooksResponse400Error
from .post_by_org_by_repo_webhooks_response_400_error_details import PostByOrgByRepoWebhooksResponse400ErrorDetails
from .post_by_org_by_repo_webhooks_response_401 import PostByOrgByRepoWebhooksResponse401
from .post_by_org_by_repo_webhooks_response_401_error import PostByOrgByRepoWebhooksResponse401Error
from .post_by_org_by_repo_webhooks_response_401_error_details import PostByOrgByRepoWebhooksResponse401ErrorDetails
from .post_by_org_by_repo_webhooks_response_403 import PostByOrgByRepoWebhooksResponse403
from .post_by_org_by_repo_webhooks_response_403_error import PostByOrgByRepoWebhooksResponse403Error
from .post_by_org_by_repo_webhooks_response_403_error_details import PostByOrgByRepoWebhooksResponse403ErrorDetails
from .post_by_org_by_repo_webhooks_response_404 import PostByOrgByRepoWebhooksResponse404
from .post_by_org_by_repo_webhooks_response_404_error import PostByOrgByRepoWebhooksResponse404Error
from .post_by_org_by_repo_webhooks_response_404_error_details import PostByOrgByRepoWebhooksResponse404ErrorDetails
from .post_by_org_by_repo_webhooks_response_406 import PostByOrgByRepoWebhooksResponse406
from .post_by_org_by_repo_webhooks_response_406_error import PostByOrgByRepoWebhooksResponse406Error
from .post_by_org_by_repo_webhooks_response_406_error_details import PostByOrgByRepoWebhooksResponse406ErrorDetails
from .post_by_org_by_repo_webhooks_response_409 import PostByOrgByRepoWebhooksResponse409
from .post_by_org_by_repo_webhooks_response_409_error import PostByOrgByRepoWebhooksResponse409Error
from .post_by_org_by_repo_webhooks_response_409_error_details import PostByOrgByRepoWebhooksResponse409ErrorDetails
from .post_by_org_by_repo_webhooks_response_500 import PostByOrgByRepoWebhooksResponse500
from .post_by_org_by_repo_webhooks_response_500_error import PostByOrgByRepoWebhooksResponse500Error
from .post_by_org_by_repo_webhooks_response_500_error_details import PostByOrgByRepoWebhooksResponse500ErrorDetails
from .post_by_org_repos_body import PostByOrgReposBody
from .post_by_org_repos_body_upstream import PostByOrgReposBodyUpstream
from .post_by_org_repos_body_upstream_autosync_type_0 import PostByOrgReposBodyUpstreamAutosyncType0
from .post_by_org_repos_body_upstream_autosync_type_0_resolution_strategy import (
    PostByOrgReposBodyUpstreamAutosyncType0ResolutionStrategy,
)
from .post_by_org_repos_response_201 import PostByOrgReposResponse201
from .post_by_org_repos_response_201_upstream_type_0 import PostByOrgReposResponse201UpstreamType0
from .post_by_org_repos_response_201_upstream_type_0_autosync_type_0 import (
    PostByOrgReposResponse201UpstreamType0AutosyncType0,
)
from .post_by_org_repos_response_201_upstream_type_0_autosync_type_0_resolution_strategy import (
    PostByOrgReposResponse201UpstreamType0AutosyncType0ResolutionStrategy,
)
from .post_by_org_repos_response_400 import PostByOrgReposResponse400
from .post_by_org_repos_response_400_error import PostByOrgReposResponse400Error
from .post_by_org_repos_response_400_error_details import PostByOrgReposResponse400ErrorDetails
from .post_by_org_repos_response_401 import PostByOrgReposResponse401
from .post_by_org_repos_response_401_error import PostByOrgReposResponse401Error
from .post_by_org_repos_response_401_error_details import PostByOrgReposResponse401ErrorDetails
from .post_by_org_repos_response_403 import PostByOrgReposResponse403
from .post_by_org_repos_response_403_error import PostByOrgReposResponse403Error
from .post_by_org_repos_response_403_error_details import PostByOrgReposResponse403ErrorDetails
from .post_by_org_repos_response_404 import PostByOrgReposResponse404
from .post_by_org_repos_response_404_error import PostByOrgReposResponse404Error
from .post_by_org_repos_response_404_error_details import PostByOrgReposResponse404ErrorDetails
from .post_by_org_repos_response_406 import PostByOrgReposResponse406
from .post_by_org_repos_response_406_error import PostByOrgReposResponse406Error
from .post_by_org_repos_response_406_error_details import PostByOrgReposResponse406ErrorDetails
from .post_by_org_repos_response_409 import PostByOrgReposResponse409
from .post_by_org_repos_response_409_error import PostByOrgReposResponse409Error
from .post_by_org_repos_response_409_error_details import PostByOrgReposResponse409ErrorDetails
from .post_by_org_repos_response_500 import PostByOrgReposResponse500
from .post_by_org_repos_response_500_error import PostByOrgReposResponse500Error
from .post_by_org_repos_response_500_error_details import PostByOrgReposResponse500ErrorDetails

__all__ = (
    "DeleteByOrgApiKeysByIdResponse200",
    "DeleteByOrgApiKeysByIdResponse400",
    "DeleteByOrgApiKeysByIdResponse400Error",
    "DeleteByOrgApiKeysByIdResponse400ErrorDetails",
    "DeleteByOrgApiKeysByIdResponse401",
    "DeleteByOrgApiKeysByIdResponse401Error",
    "DeleteByOrgApiKeysByIdResponse401ErrorDetails",
    "DeleteByOrgApiKeysByIdResponse403",
    "DeleteByOrgApiKeysByIdResponse403Error",
    "DeleteByOrgApiKeysByIdResponse403ErrorDetails",
    "DeleteByOrgApiKeysByIdResponse404",
    "DeleteByOrgApiKeysByIdResponse404Error",
    "DeleteByOrgApiKeysByIdResponse404ErrorDetails",
    "DeleteByOrgApiKeysByIdResponse406",
    "DeleteByOrgApiKeysByIdResponse406Error",
    "DeleteByOrgApiKeysByIdResponse406ErrorDetails",
    "DeleteByOrgApiKeysByIdResponse409",
    "DeleteByOrgApiKeysByIdResponse409Error",
    "DeleteByOrgApiKeysByIdResponse409ErrorDetails",
    "DeleteByOrgApiKeysByIdResponse500",
    "DeleteByOrgApiKeysByIdResponse500Error",
    "DeleteByOrgApiKeysByIdResponse500ErrorDetails",
    "DeleteByOrgByRepoBranchesByBranchResponse200",
    "DeleteByOrgByRepoBranchesByBranchResponse400",
    "DeleteByOrgByRepoBranchesByBranchResponse400Error",
    "DeleteByOrgByRepoBranchesByBranchResponse400ErrorDetails",
    "DeleteByOrgByRepoBranchesByBranchResponse401",
    "DeleteByOrgByRepoBranchesByBranchResponse401Error",
    "DeleteByOrgByRepoBranchesByBranchResponse401ErrorDetails",
    "DeleteByOrgByRepoBranchesByBranchResponse403",
    "DeleteByOrgByRepoBranchesByBranchResponse403Error",
    "DeleteByOrgByRepoBranchesByBranchResponse403ErrorDetails",
    "DeleteByOrgByRepoBranchesByBranchResponse404",
    "DeleteByOrgByRepoBranchesByBranchResponse404Error",
    "DeleteByOrgByRepoBranchesByBranchResponse404ErrorDetails",
    "DeleteByOrgByRepoBranchesByBranchResponse406",
    "DeleteByOrgByRepoBranchesByBranchResponse406Error",
    "DeleteByOrgByRepoBranchesByBranchResponse406ErrorDetails",
    "DeleteByOrgByRepoBranchesByBranchResponse409",
    "DeleteByOrgByRepoBranchesByBranchResponse409Error",
    "DeleteByOrgByRepoBranchesByBranchResponse409ErrorDetails",
    "DeleteByOrgByRepoBranchesByBranchResponse500",
    "DeleteByOrgByRepoBranchesByBranchResponse500Error",
    "DeleteByOrgByRepoBranchesByBranchResponse500ErrorDetails",
    "DeleteByOrgByRepoResponse200",
    "DeleteByOrgByRepoResponse400",
    "DeleteByOrgByRepoResponse400Error",
    "DeleteByOrgByRepoResponse400ErrorDetails",
    "DeleteByOrgByRepoResponse401",
    "DeleteByOrgByRepoResponse401Error",
    "DeleteByOrgByRepoResponse401ErrorDetails",
    "DeleteByOrgByRepoResponse403",
    "DeleteByOrgByRepoResponse403Error",
    "DeleteByOrgByRepoResponse403ErrorDetails",
    "DeleteByOrgByRepoResponse404",
    "DeleteByOrgByRepoResponse404Error",
    "DeleteByOrgByRepoResponse404ErrorDetails",
    "DeleteByOrgByRepoResponse406",
    "DeleteByOrgByRepoResponse406Error",
    "DeleteByOrgByRepoResponse406ErrorDetails",
    "DeleteByOrgByRepoResponse409",
    "DeleteByOrgByRepoResponse409Error",
    "DeleteByOrgByRepoResponse409ErrorDetails",
    "DeleteByOrgByRepoResponse500",
    "DeleteByOrgByRepoResponse500Error",
    "DeleteByOrgByRepoResponse500ErrorDetails",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse200",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse400",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse400Error",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse400ErrorDetails",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse401",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse401Error",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse401ErrorDetails",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse403",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse403Error",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse403ErrorDetails",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse404",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse404Error",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse404ErrorDetails",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse406",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse406Error",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse406ErrorDetails",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse409",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse409Error",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse409ErrorDetails",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse500",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse500Error",
    "DeleteByOrgByRepoWebhooksByWebhookIdResponse500ErrorDetails",
    "GetByOrgApiKeysResponse200",
    "GetByOrgApiKeysResponse200ApiKeysItem",
    "GetByOrgApiKeysResponse400",
    "GetByOrgApiKeysResponse400Error",
    "GetByOrgApiKeysResponse400ErrorDetails",
    "GetByOrgApiKeysResponse401",
    "GetByOrgApiKeysResponse401Error",
    "GetByOrgApiKeysResponse401ErrorDetails",
    "GetByOrgApiKeysResponse403",
    "GetByOrgApiKeysResponse403Error",
    "GetByOrgApiKeysResponse403ErrorDetails",
    "GetByOrgApiKeysResponse404",
    "GetByOrgApiKeysResponse404Error",
    "GetByOrgApiKeysResponse404ErrorDetails",
    "GetByOrgApiKeysResponse406",
    "GetByOrgApiKeysResponse406Error",
    "GetByOrgApiKeysResponse406ErrorDetails",
    "GetByOrgApiKeysResponse409",
    "GetByOrgApiKeysResponse409Error",
    "GetByOrgApiKeysResponse409ErrorDetails",
    "GetByOrgApiKeysResponse500",
    "GetByOrgApiKeysResponse500Error",
    "GetByOrgApiKeysResponse500ErrorDetails",
    "GetByOrgByRepoBranchesResponse200",
    "GetByOrgByRepoBranchesResponse200BranchesItem",
    "GetByOrgByRepoBranchesResponse400",
    "GetByOrgByRepoBranchesResponse400Error",
    "GetByOrgByRepoBranchesResponse400ErrorDetails",
    "GetByOrgByRepoBranchesResponse401",
    "GetByOrgByRepoBranchesResponse401Error",
    "GetByOrgByRepoBranchesResponse401ErrorDetails",
    "GetByOrgByRepoBranchesResponse403",
    "GetByOrgByRepoBranchesResponse403Error",
    "GetByOrgByRepoBranchesResponse403ErrorDetails",
    "GetByOrgByRepoBranchesResponse404",
    "GetByOrgByRepoBranchesResponse404Error",
    "GetByOrgByRepoBranchesResponse404ErrorDetails",
    "GetByOrgByRepoBranchesResponse406",
    "GetByOrgByRepoBranchesResponse406Error",
    "GetByOrgByRepoBranchesResponse406ErrorDetails",
    "GetByOrgByRepoBranchesResponse409",
    "GetByOrgByRepoBranchesResponse409Error",
    "GetByOrgByRepoBranchesResponse409ErrorDetails",
    "GetByOrgByRepoBranchesResponse500",
    "GetByOrgByRepoBranchesResponse500Error",
    "GetByOrgByRepoBranchesResponse500ErrorDetails",
    "GetByOrgByRepoCommitsByShaResponse200",
    "GetByOrgByRepoCommitsByShaResponse200Author",
    "GetByOrgByRepoCommitsByShaResponse200Committer",
    "GetByOrgByRepoCommitsByShaResponse400",
    "GetByOrgByRepoCommitsByShaResponse400Error",
    "GetByOrgByRepoCommitsByShaResponse400ErrorDetails",
    "GetByOrgByRepoCommitsByShaResponse401",
    "GetByOrgByRepoCommitsByShaResponse401Error",
    "GetByOrgByRepoCommitsByShaResponse401ErrorDetails",
    "GetByOrgByRepoCommitsByShaResponse403",
    "GetByOrgByRepoCommitsByShaResponse403Error",
    "GetByOrgByRepoCommitsByShaResponse403ErrorDetails",
    "GetByOrgByRepoCommitsByShaResponse404",
    "GetByOrgByRepoCommitsByShaResponse404Error",
    "GetByOrgByRepoCommitsByShaResponse404ErrorDetails",
    "GetByOrgByRepoCommitsByShaResponse406",
    "GetByOrgByRepoCommitsByShaResponse406Error",
    "GetByOrgByRepoCommitsByShaResponse406ErrorDetails",
    "GetByOrgByRepoCommitsByShaResponse409",
    "GetByOrgByRepoCommitsByShaResponse409Error",
    "GetByOrgByRepoCommitsByShaResponse409ErrorDetails",
    "GetByOrgByRepoCommitsByShaResponse500",
    "GetByOrgByRepoCommitsByShaResponse500Error",
    "GetByOrgByRepoCommitsByShaResponse500ErrorDetails",
    "GetByOrgByRepoCommitsResponse200",
    "GetByOrgByRepoCommitsResponse200CommitsItem",
    "GetByOrgByRepoCommitsResponse200CommitsItemAuthor",
    "GetByOrgByRepoCommitsResponse200CommitsItemCommitter",
    "GetByOrgByRepoCommitsResponse400",
    "GetByOrgByRepoCommitsResponse400Error",
    "GetByOrgByRepoCommitsResponse400ErrorDetails",
    "GetByOrgByRepoCommitsResponse401",
    "GetByOrgByRepoCommitsResponse401Error",
    "GetByOrgByRepoCommitsResponse401ErrorDetails",
    "GetByOrgByRepoCommitsResponse403",
    "GetByOrgByRepoCommitsResponse403Error",
    "GetByOrgByRepoCommitsResponse403ErrorDetails",
    "GetByOrgByRepoCommitsResponse404",
    "GetByOrgByRepoCommitsResponse404Error",
    "GetByOrgByRepoCommitsResponse404ErrorDetails",
    "GetByOrgByRepoCommitsResponse406",
    "GetByOrgByRepoCommitsResponse406Error",
    "GetByOrgByRepoCommitsResponse406ErrorDetails",
    "GetByOrgByRepoCommitsResponse409",
    "GetByOrgByRepoCommitsResponse409Error",
    "GetByOrgByRepoCommitsResponse409ErrorDetails",
    "GetByOrgByRepoCommitsResponse500",
    "GetByOrgByRepoCommitsResponse500Error",
    "GetByOrgByRepoCommitsResponse500ErrorDetails",
    "GetByOrgByRepoContentResponse200Type0",
    "GetByOrgByRepoContentResponse200Type1",
    "GetByOrgByRepoContentResponse200Type2",
    "GetByOrgByRepoContentResponse200Type2EntriesItemType0",
    "GetByOrgByRepoContentResponse200Type2EntriesItemType1",
    "GetByOrgByRepoContentResponse200Type2EntriesItemType2",
    "GetByOrgByRepoContentResponse400",
    "GetByOrgByRepoContentResponse400Error",
    "GetByOrgByRepoContentResponse400ErrorDetails",
    "GetByOrgByRepoContentResponse401",
    "GetByOrgByRepoContentResponse401Error",
    "GetByOrgByRepoContentResponse401ErrorDetails",
    "GetByOrgByRepoContentResponse403",
    "GetByOrgByRepoContentResponse403Error",
    "GetByOrgByRepoContentResponse403ErrorDetails",
    "GetByOrgByRepoContentResponse404",
    "GetByOrgByRepoContentResponse404Error",
    "GetByOrgByRepoContentResponse404ErrorDetails",
    "GetByOrgByRepoContentResponse406",
    "GetByOrgByRepoContentResponse406Error",
    "GetByOrgByRepoContentResponse406ErrorDetails",
    "GetByOrgByRepoContentResponse409",
    "GetByOrgByRepoContentResponse409Error",
    "GetByOrgByRepoContentResponse409ErrorDetails",
    "GetByOrgByRepoContentResponse500",
    "GetByOrgByRepoContentResponse500Error",
    "GetByOrgByRepoContentResponse500ErrorDetails",
    "GetByOrgByRepoResponse200",
    "GetByOrgByRepoResponse200UpstreamType0",
    "GetByOrgByRepoResponse200UpstreamType0AutosyncType0",
    "GetByOrgByRepoResponse200UpstreamType0AutosyncType0ResolutionStrategy",
    "GetByOrgByRepoResponse400",
    "GetByOrgByRepoResponse400Error",
    "GetByOrgByRepoResponse400ErrorDetails",
    "GetByOrgByRepoResponse401",
    "GetByOrgByRepoResponse401Error",
    "GetByOrgByRepoResponse401ErrorDetails",
    "GetByOrgByRepoResponse403",
    "GetByOrgByRepoResponse403Error",
    "GetByOrgByRepoResponse403ErrorDetails",
    "GetByOrgByRepoResponse404",
    "GetByOrgByRepoResponse404Error",
    "GetByOrgByRepoResponse404ErrorDetails",
    "GetByOrgByRepoResponse406",
    "GetByOrgByRepoResponse406Error",
    "GetByOrgByRepoResponse406ErrorDetails",
    "GetByOrgByRepoResponse409",
    "GetByOrgByRepoResponse409Error",
    "GetByOrgByRepoResponse409ErrorDetails",
    "GetByOrgByRepoResponse500",
    "GetByOrgByRepoResponse500Error",
    "GetByOrgByRepoResponse500ErrorDetails",
    "GetByOrgByRepoWebhooksResponse200",
    "GetByOrgByRepoWebhooksResponse200WebhooksItem",
    "GetByOrgByRepoWebhooksResponse200WebhooksItemEventsItem",
    "GetByOrgByRepoWebhooksResponse400",
    "GetByOrgByRepoWebhooksResponse400Error",
    "GetByOrgByRepoWebhooksResponse400ErrorDetails",
    "GetByOrgByRepoWebhooksResponse401",
    "GetByOrgByRepoWebhooksResponse401Error",
    "GetByOrgByRepoWebhooksResponse401ErrorDetails",
    "GetByOrgByRepoWebhooksResponse403",
    "GetByOrgByRepoWebhooksResponse403Error",
    "GetByOrgByRepoWebhooksResponse403ErrorDetails",
    "GetByOrgByRepoWebhooksResponse404",
    "GetByOrgByRepoWebhooksResponse404Error",
    "GetByOrgByRepoWebhooksResponse404ErrorDetails",
    "GetByOrgByRepoWebhooksResponse406",
    "GetByOrgByRepoWebhooksResponse406Error",
    "GetByOrgByRepoWebhooksResponse406ErrorDetails",
    "GetByOrgByRepoWebhooksResponse409",
    "GetByOrgByRepoWebhooksResponse409Error",
    "GetByOrgByRepoWebhooksResponse409ErrorDetails",
    "GetByOrgByRepoWebhooksResponse500",
    "GetByOrgByRepoWebhooksResponse500Error",
    "GetByOrgByRepoWebhooksResponse500ErrorDetails",
    "GetByOrgReposResponse200",
    "GetByOrgReposResponse200ReposItem",
    "GetByOrgReposResponse200ReposItemUpstreamType0",
    "GetByOrgReposResponse200ReposItemUpstreamType0AutosyncType0",
    "GetByOrgReposResponse200ReposItemUpstreamType0AutosyncType0ResolutionStrategy",
    "GetByOrgReposResponse400",
    "GetByOrgReposResponse400Error",
    "GetByOrgReposResponse400ErrorDetails",
    "GetByOrgReposResponse401",
    "GetByOrgReposResponse401Error",
    "GetByOrgReposResponse401ErrorDetails",
    "GetByOrgReposResponse403",
    "GetByOrgReposResponse403Error",
    "GetByOrgReposResponse403ErrorDetails",
    "GetByOrgReposResponse404",
    "GetByOrgReposResponse404Error",
    "GetByOrgReposResponse404ErrorDetails",
    "GetByOrgReposResponse406",
    "GetByOrgReposResponse406Error",
    "GetByOrgReposResponse406ErrorDetails",
    "GetByOrgReposResponse409",
    "GetByOrgReposResponse409Error",
    "GetByOrgReposResponse409ErrorDetails",
    "GetByOrgReposResponse500",
    "GetByOrgReposResponse500Error",
    "GetByOrgReposResponse500ErrorDetails",
    "GetByOrgResponse200",
    "GetByOrgResponse400",
    "GetByOrgResponse400Error",
    "GetByOrgResponse400ErrorDetails",
    "GetByOrgResponse401",
    "GetByOrgResponse401Error",
    "GetByOrgResponse401ErrorDetails",
    "GetByOrgResponse403",
    "GetByOrgResponse403Error",
    "GetByOrgResponse403ErrorDetails",
    "GetByOrgResponse404",
    "GetByOrgResponse404Error",
    "GetByOrgResponse404ErrorDetails",
    "GetByOrgResponse406",
    "GetByOrgResponse406Error",
    "GetByOrgResponse406ErrorDetails",
    "GetByOrgResponse409",
    "GetByOrgResponse409Error",
    "GetByOrgResponse409ErrorDetails",
    "GetByOrgResponse500",
    "GetByOrgResponse500Error",
    "GetByOrgResponse500ErrorDetails",
    "PatchByOrgByRepoBody",
    "PatchByOrgByRepoBodyUpstreamType0",
    "PatchByOrgByRepoBodyUpstreamType0AutosyncType0",
    "PatchByOrgByRepoBodyUpstreamType0AutosyncType0ResolutionStrategy",
    "PatchByOrgByRepoResponse200",
    "PatchByOrgByRepoResponse200UpstreamType0",
    "PatchByOrgByRepoResponse200UpstreamType0AutosyncType0",
    "PatchByOrgByRepoResponse200UpstreamType0AutosyncType0ResolutionStrategy",
    "PatchByOrgByRepoResponse400",
    "PatchByOrgByRepoResponse400Error",
    "PatchByOrgByRepoResponse400ErrorDetails",
    "PatchByOrgByRepoResponse401",
    "PatchByOrgByRepoResponse401Error",
    "PatchByOrgByRepoResponse401ErrorDetails",
    "PatchByOrgByRepoResponse403",
    "PatchByOrgByRepoResponse403Error",
    "PatchByOrgByRepoResponse403ErrorDetails",
    "PatchByOrgByRepoResponse404",
    "PatchByOrgByRepoResponse404Error",
    "PatchByOrgByRepoResponse404ErrorDetails",
    "PatchByOrgByRepoResponse406",
    "PatchByOrgByRepoResponse406Error",
    "PatchByOrgByRepoResponse406ErrorDetails",
    "PatchByOrgByRepoResponse409",
    "PatchByOrgByRepoResponse409Error",
    "PatchByOrgByRepoResponse409ErrorDetails",
    "PatchByOrgByRepoResponse500",
    "PatchByOrgByRepoResponse500Error",
    "PatchByOrgByRepoResponse500ErrorDetails",
    "PostByOrgApiKeysBody",
    "PostByOrgApiKeysBodyScopesItem",
    "PostByOrgApiKeysResponse201",
    "PostByOrgApiKeysResponse400",
    "PostByOrgApiKeysResponse400Error",
    "PostByOrgApiKeysResponse400ErrorDetails",
    "PostByOrgApiKeysResponse401",
    "PostByOrgApiKeysResponse401Error",
    "PostByOrgApiKeysResponse401ErrorDetails",
    "PostByOrgApiKeysResponse403",
    "PostByOrgApiKeysResponse403Error",
    "PostByOrgApiKeysResponse403ErrorDetails",
    "PostByOrgApiKeysResponse404",
    "PostByOrgApiKeysResponse404Error",
    "PostByOrgApiKeysResponse404ErrorDetails",
    "PostByOrgApiKeysResponse406",
    "PostByOrgApiKeysResponse406Error",
    "PostByOrgApiKeysResponse406ErrorDetails",
    "PostByOrgApiKeysResponse409",
    "PostByOrgApiKeysResponse409Error",
    "PostByOrgApiKeysResponse409ErrorDetails",
    "PostByOrgApiKeysResponse500",
    "PostByOrgApiKeysResponse500Error",
    "PostByOrgApiKeysResponse500ErrorDetails",
    "PostByOrgByRepoBranchesBody",
    "PostByOrgByRepoBranchesResponse201",
    "PostByOrgByRepoBranchesResponse400",
    "PostByOrgByRepoBranchesResponse400Error",
    "PostByOrgByRepoBranchesResponse400ErrorDetails",
    "PostByOrgByRepoBranchesResponse401",
    "PostByOrgByRepoBranchesResponse401Error",
    "PostByOrgByRepoBranchesResponse401ErrorDetails",
    "PostByOrgByRepoBranchesResponse403",
    "PostByOrgByRepoBranchesResponse403Error",
    "PostByOrgByRepoBranchesResponse403ErrorDetails",
    "PostByOrgByRepoBranchesResponse404",
    "PostByOrgByRepoBranchesResponse404Error",
    "PostByOrgByRepoBranchesResponse404ErrorDetails",
    "PostByOrgByRepoBranchesResponse406",
    "PostByOrgByRepoBranchesResponse406Error",
    "PostByOrgByRepoBranchesResponse406ErrorDetails",
    "PostByOrgByRepoBranchesResponse409",
    "PostByOrgByRepoBranchesResponse409Error",
    "PostByOrgByRepoBranchesResponse409ErrorDetails",
    "PostByOrgByRepoBranchesResponse500",
    "PostByOrgByRepoBranchesResponse500Error",
    "PostByOrgByRepoBranchesResponse500ErrorDetails",
    "PostByOrgByRepoWebhooksBody",
    "PostByOrgByRepoWebhooksBodyEventsItem",
    "PostByOrgByRepoWebhooksResponse201",
    "PostByOrgByRepoWebhooksResponse201EventsItem",
    "PostByOrgByRepoWebhooksResponse400",
    "PostByOrgByRepoWebhooksResponse400Error",
    "PostByOrgByRepoWebhooksResponse400ErrorDetails",
    "PostByOrgByRepoWebhooksResponse401",
    "PostByOrgByRepoWebhooksResponse401Error",
    "PostByOrgByRepoWebhooksResponse401ErrorDetails",
    "PostByOrgByRepoWebhooksResponse403",
    "PostByOrgByRepoWebhooksResponse403Error",
    "PostByOrgByRepoWebhooksResponse403ErrorDetails",
    "PostByOrgByRepoWebhooksResponse404",
    "PostByOrgByRepoWebhooksResponse404Error",
    "PostByOrgByRepoWebhooksResponse404ErrorDetails",
    "PostByOrgByRepoWebhooksResponse406",
    "PostByOrgByRepoWebhooksResponse406Error",
    "PostByOrgByRepoWebhooksResponse406ErrorDetails",
    "PostByOrgByRepoWebhooksResponse409",
    "PostByOrgByRepoWebhooksResponse409Error",
    "PostByOrgByRepoWebhooksResponse409ErrorDetails",
    "PostByOrgByRepoWebhooksResponse500",
    "PostByOrgByRepoWebhooksResponse500Error",
    "PostByOrgByRepoWebhooksResponse500ErrorDetails",
    "PostByOrgReposBody",
    "PostByOrgReposBodyUpstream",
    "PostByOrgReposBodyUpstreamAutosyncType0",
    "PostByOrgReposBodyUpstreamAutosyncType0ResolutionStrategy",
    "PostByOrgReposResponse201",
    "PostByOrgReposResponse201UpstreamType0",
    "PostByOrgReposResponse201UpstreamType0AutosyncType0",
    "PostByOrgReposResponse201UpstreamType0AutosyncType0ResolutionStrategy",
    "PostByOrgReposResponse400",
    "PostByOrgReposResponse400Error",
    "PostByOrgReposResponse400ErrorDetails",
    "PostByOrgReposResponse401",
    "PostByOrgReposResponse401Error",
    "PostByOrgReposResponse401ErrorDetails",
    "PostByOrgReposResponse403",
    "PostByOrgReposResponse403Error",
    "PostByOrgReposResponse403ErrorDetails",
    "PostByOrgReposResponse404",
    "PostByOrgReposResponse404Error",
    "PostByOrgReposResponse404ErrorDetails",
    "PostByOrgReposResponse406",
    "PostByOrgReposResponse406Error",
    "PostByOrgReposResponse406ErrorDetails",
    "PostByOrgReposResponse409",
    "PostByOrgReposResponse409Error",
    "PostByOrgReposResponse409ErrorDetails",
    "PostByOrgReposResponse500",
    "PostByOrgReposResponse500Error",
    "PostByOrgReposResponse500ErrorDetails",
)
